dashboard/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from users.views import CustomLoginView, ChangePasswordView
from users.forms import LoginForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('users.urls')),
    path('login/', CustomLoginView.as_view(redirect_authenticated_user=True, template_name='users/login.html',
                                           authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-change/', ChangePasswordView.as_view(), name='password-change'),
    path('api/', include('user_apps.urls'))
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.home, name='home'),
    path('register/',views.RegisterView.as_view(), name='user-register'),
]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class RegisterForm(UserCreationForm):
    # fields that are included and customized in our register form
    first_name = forms.CharField(max_length=100,
                                 required=True,
                                 widget=forms.TextInput(attrs={'placeholder': 'First Name',
                                                               'class': 'form-control',
                                                               }))
    last_name = forms.CharField(max_length=100,
                                required=True,
                                widget=forms.TextInput(attrs={'placeholder': 'Last Name',
                                                              'class': 'form-control',
                                                              }))
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'placeholder': 'Username',
                                                             'class': 'form-control',
                                                             }))
    email = forms.EmailField(required=True,
                             widget=forms.TextInput(attrs={'placeholder': 'Email',
                                                           'class': 'form-control',
                                                           }))
    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Password',
                                                                  'class': 'form-control',
                                                                  'data-toggle': 'password',
                                                                  'id': 'password',
                                                                  }))
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password',
                                                                  'class': 'form-control',
                                                                  'data-toggle': 'password',
                                                                  'id': 'password',
                                                                  }))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']

class LoginForm(AuthenticationForm):
    # authenticating fields provided by user in login form
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'placeholder': 'Username',
                                                             'class': 'form-control',
                                                             }))
    password = forms.CharField(max_length=50,
                               required=True,
                               widget=forms.PasswordInput(attrs={'placeholder': 'Password',
                                                                 'class': 'form-control',
                                                                 'data-toggle': 'password',
                                                                 'id': 'password',
                                                                 'name': 'password',
                                                                 }))
    remember_me = forms.BooleanField(required=False)

    class Meta:
        model = User
        fields = ['username', 'password', 'remember_me']

users/views.py
from typing import Any
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from django.template.response import TemplateResponse
from django.core.handlers.wsgi import WSGIRequest
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib import messages
from django.views import View
from .forms import RegisterForm, LoginForm

# Create your views here.
def home(request):
    return render(request, 'users/home.html')

class RegisterView(View):
    form_class = RegisterForm
    initial = {'key': 'value'}
    template_name = 'users/register.html'

    def dispatch(self, request, *args, **kwargs):
        # will redirect to the home page if a user tries to access the register page while logged in
        if request.user.is_authenticated:
            return redirect(to='/')

        # else process dispatch as it otherwise normally would
        return super(RegisterView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            form.save()

            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}')

            return redirect(to='login')

        return render(request, self.template_name, {'form': form})
    
# Class based view that extends from the built in login view to add a remember me functionality
class CustomLoginView(LoginView):
    form_class = LoginForm

    def form_valid(self, form):
        remember_me = form.cleaned_data.get('remember_me')

        if not remember_me:
            # set session expiry to 0 seconds. So it will automatically close the session after the browser is closed.
            self.request.session.set_expiry(0)

            # Set session as modified to force data updates/cookie to be saved.
            self.request.session.modified = True

        # else browser session will be as long as the session cookie time "SESSION_COOKIE_AGE" defined in settings.py
        return super(CustomLoginView, self).form_valid(form)

class ChangePasswordView(SuccessMessageMixin, PasswordChangeView):
    template_name = 'users/change_password.html'
    success_message = "Successfully Changed Your Password"
    success_url = reverse_lazy('users:home')

users/templates/users/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Meta Tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">

    <!-- Boostrap CDN CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    <!-- Show Password CSS -->
    <link rel="stylesheet" href="{% static 'users/css/show-password-toggle.min.css' %}">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'users/css/main.css' %}">
    
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    <div class="container p-3 my-3">
        <div class="row">
          <div class="col-md-12">
            <nav class="navbar navbar-expand-md navbar-light px-3 mb-3" style="background-color: #f0f5f5">
              <a href="{% url 'users:home' %}" class="navbar-brand">
                {% if user.is_authenticated %}
                  DASHBOARD
                {% else %}
                  HOME
                {% endif %}
              </a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <div class="navbar-nav ms-auto">
                      {% if user.is_authenticated %}
                        <small>
                          <a href="{% url 'password-change' %}" class="nav-item nav-link me-3">Reset Password</a>
                        </small>
                        <form action="{% url 'logout' %}" method="post">
                          {% csrf_token %}
                          <button type="submit" class="btn btn-outline-success me-2">Logout</button>
                        </form>   
                      {% else %}
                        <a href="{% url 'login' %}" class="btn btn-outline-dark me-2">Sign in</a>
                      {% endif %}
                    </div>
                </div>
            </nav>
            <!--Any flash messages pop up in any page because this is the base template-->
            {% if messages %}
              <div class="alert alert-dismissible" role="alert">
                {% for message in messages %}
                  <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                {% endfor %}
                <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            {% endif %}
            {% block content %}{% endblock %}
          </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.7.1.slim.js" integrity="sha256-UgvvN8vBkgO0luPSUl2s8TIlOSYRoGFAX4jlCIm9Adc=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js" integrity="sha512-2rNj2KJ+D8s1ceNasTIex6z4HWyOnEYLVC3FigGOmyQCZc2eBXKgOxQmo3oKLHyfcj53uz4QMsRCWNbLd32Q1g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <!-- Show Password Toggle -->
    <script src="{% static 'users/js/show-password-toggle.min.js' %}"></script>
</body>
</html>

users/templates/users/change_password.html
{% extends "users/base.html" %}
{% block content %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                        <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                            <div class="card-header justify-content-center">
                              <h3 class="font-weight-light my-4 text-center">Change Your Password</h3>
                            </div>
                            {% if form.errors %}
                                <div class="alert alert-danger alert-dismissible" role="alert">
                                    <div id="form_errors">
                                        {% for key, value in form.errors.items %}
                                            <strong>{{ value }}</strong>
                                        {% endfor %}
                                    </div>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            {% endif %}

                            <div class="card-body">
                                <form method="POST">
                                    {% csrf_token %}
                                        <div class="col-md-10 offset-md-1 mb-3">
                                            <div class="form-group">
                                                <input type="password" name="old_password" autocomplete="new-password"
                                                       class="form-control" required id="id_old_password"
                                                       placeholder="Enter Old Password"/>
                                                <span>
                                                </span>
                                            </div>
                                        </div>
                                        <div class="col-md-10 offset-md-1 mb-3">
                                            <div class="form-group">
                                                <input type="password" name="new_password1" autocomplete="new-password"
                                                       class="form-control" required id="id_new_password1"
                                                       placeholder="Enter New Password"/>
                                                <span>
                                                </span>
                                            </div>
                                        </div>
                                        <div class="col-md-10 offset-md-1 mb-3">
                                            <div class="form-group">
                                                <input type="password" name="new_password2" autocomplete="new-password"
                                                       required id="id_new_password2" class="form-control"
                                                       placeholder="Confirm New Password"/>
                                            </div>
                                        </div>
                                    <div class="row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group mt-0 mb-1">
                                                <button type="submit" class="col-md-12 btn btn-dark" id="reset">Update Password</button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

users/templates/users/dashboard.html
{% load static %}
<div class="row dashboard-cards d-flex justify-content-center">
  <div class="col-lg-4 col-sm-6 col-12">
    <a href="/api/apps/">
      <div class="card">
        <img class="card-img" src="{% static 'users/images/2760274.jpg' %}" alt="Apps">
        <div class="card-img-overlay">
          <h3 class="card-title">APPS</h3>
        </div>
      </div>
    </a>
  </div>
  <div class="col-lg-4 col-sm-6 col-12">
    <a href="/api/subscriptions/">
      <div class="card">
        <img class="card-img" src="{% static 'users/images/9834595.jpg' %}" alt="Subscription">
        <div class="card-img-overlay">
          <h3 class="card-title">SUBSCRIPTION</h3>
        </div>
      </div>
    </a>
  </div>
  <div class="col-lg-4 col-sm-6 col-12">
    <a href="/api/plans/">
      <div class="card">
        <img class="card-img" src="{% static 'users/images/2116313.jpg' %}" alt="Pricing">
        <div class="card-img-overlay">
          <h3 class="card-title">PRICING PLAN</h3>
        </div>
      </div>
    </a>
  </div>
</div>  

users/templates/users/home.html
{% extends "users/base.html" %}
{% block title %} Home Page {% endblock title%}
{% block content %}
    <div class="jumbotron my-4">
        <h1 class="display-6">Welcome, {{user.username.title|default:'Guest'|upper}}</h1>
        {% if user.is_authenticated %}
            <hr class="my-4">
            {% include "users/dashboard.html" %}
        {% else %}
            <p class="lead">
                This is a <b>Backend Service,</b> which will expose a set of <b>Rest API</b> endpoints.
                User could perform CRUD operations to his/her apps by associating a subscription with a pricing plan.
            </p>
            <hr class="my-4">
        {% endif %}
    </div>

{% endblock content %}

users/templates/users/login.html
{% extends "users/base.html" %}
{% block title %} Login Page {% endblock title%}
{% block content %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                        <div class="card-header justify-content-center">
                          <h3 class="font-weight-light my-1 text-center">Sign In</h3>
                        </div>
                        {% if form.errors %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <div id="form_errors">
                                    {% for key, value in form.errors.items %}
                                        <strong>{{ value }}</strong>
                                    {% endfor %}
                                </div>
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                                </button>
                            </div>
                        {% endif %}
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="col-md-10 offset-md-1 mb-3">
                                    <div class="input-group">
                                        {{ form.username }}
                                    </div>
                                </div>
                                <div class="col-md-10 offset-md-1 mb-3">
                                    <div class="input-group">
                                        {{ form.password }}
                                        <button id="toggle-password" type="button" class="d-none" aria-label="Show password as plain text. Warning: this will display your password on the screen.">
                                        </button>
                                    </div>
                                </div>
                                <div class="col-md-10 offset-md-1 mb-3">
                                    <div class="form-group">
                                        <!-- Add a Remember me functionality -->
                                        {{ form.remember_me }}
                                        <label> Remember me</label>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-10 offset-md-1">
                                        <div class="form-group mt-0 mb-1">
                                          <button name="login" class="col-md-12 btn btn-dark" id="login">Sign in</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small">
                                Don't have an account yet? <a href="{% url 'users:user-register' %}" class="text-decoration-none">Signup</a><br>
                                <a href="#" class="text-decoration-none"><i>Forgot Password?</i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
     </div>
{% endblock content %}

users/templates/users/logout.html
{% extends "users/base.html" %}
{% block title %}Logout{% endblock title %}
{% block content %}
    <div class="card mx-auto" style="width: 18rem;">
        <div class="card-body">
        <h5 class="card-title">You have been logged out</h5>
        <p class="card-text">
            Thanks for your time, contact me for any comments or suggestions using my email address: <b>jawad4world@gmail.com<b>
        </p>
        <br><hr><a href="{% url 'login' %}" class="btn btn-dark">Sign in again</a>
        </div>
    </div>
{% endblock content %}

users/templates/users/register.html
{% extends "users/base.html" %}
{% block title %} Register Page {% endblock title%}
{% block content %}
    <div class="form-content my-3 p-3">
		<div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-7">
                    <div class="card shadow-lg border-0 rounded-lg mt-0 mb-5">
                        <div class="card-header justify-content-center">
                        	<h3 class="font-weight-light my-4 text-center">Create Account</h3>
                        </div>
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                {% if form.errors %}
                                    <div class="alert alert-danger alert-dismissible" role="alert">
                                        <div id="form_errors">
                                            {% for key, value in form.errors.items %}
                                                <strong>{{ value }}</strong>
                                            {% endfor %}
                                        </div>
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                {% endif %}
                                <div class="row mb-3">
                                    <div class="col-md-6">
                                        <div class="input-group">
                                            {{ form.first_name }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="input-group">
                                            {{ form.last_name }}
                                        </div>
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col-md-6">
		                                <div class="input-group">
		                                    {{ form.username }}
		                                </div>
		                            </div>
                                    <div class="col-md-6">
		                                <div class="input-group">
		                                    {{ form.email }}
		                                </div>
		                            </div>
		                        </div>
                                <div class="row mb-3">
                                    <div class="col-md-6">
                                        <div class="input-group">
                                            {{ form.password1 }}
                                            {{ form.errors.password }}
                                            <button id="toggle-password" type="button" class="d-none" aria-label="Show password as plain text. Warning: this will display your password on the screen.">
                                            </button>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="input-group">
                                            {{ form.password2 }}
                                            <button id="toggle-password" type="button" class="d-none" aria-label="Show password as plain text. Warning: this will display your password on the screen.">
                                            </button>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group mt-4 mb-0">
                                    <button type="submit" class="col-md-12 btn btn-dark">Sign Up</button><br><br>
                                </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small-fs">
                                Have an account? <a href="{% url 'login' %}" class=" text-decoration-none">Sign in</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
	</div>
{% endblock content %}